### PR TITLE
Fix error while accessing JSON value

### PR DESCRIPTION
**Pull request by lahirusamith**

### CODE REVIEW

**Comment by niveathika** [comment]
@lahirusamith Do not remove most of the PR template topics, especially for new feature &. major bug fixes. It is good standard to have the fixes documented

**Comment by niveathika** [comment]
Test cases are added in https://github.com/ballerina-platform/module-ballerinax-mysql/pull/82

**Comment by lahirusamith** [comment]
> @lahirusamith Do not remove most of the PR template topics, especially for new feature &. major bug fixes. It is good standard to have the fixes documented

@niveathika Sorry! Shall I add the template topics again then?

**Comment by niveathika** [comment]
> > @lahirusamith Do not remove most of the PR template topics, especially for new feature &. major bug fixes. It is good standard to have the fixes documented
> 
> @niveathika Sorry! Shall I add the template topics again then?

Its fine for the this Pull Request. Let's follow from the next one on

**Review by niveathika — APPROVED** [review]

**Pull request merged**
